### ISSUE TITLE
on windows 8.1 escape sequence is not working and moves not printing in human v bot

### ISSUE THREAD

**Issue by rtayek** [maxpumperla/deep_learning_and_the_game_of_go#10]
the boards print and scroll (the screen is not cleared).
the moves in bot v bot do get printed while the moves in human v bot do _not_ get printed.

**Comment by hackf5** [comment]
This function works on both Windows and Linux

```
def clear_screen():
    if platform.system() == "Windows":
        subprocess.Popen("cls", shell=True).communicate()
    else:  # Linux and Mac
        print("\033c", end="")
```

**Comment by maxpumperla** [comment]
@hackf5 or @rtayek would you mind sending a PR for this fix? sorry about that, neither @macfergus nor I work with windows.

**Comment by hackf5** [comment]
Will do.
