### ISSUE TITLE
Loading pickled version of mnist crashes on python 3

### ISSUE THREAD

**Issue by jeffhgs** [maxpumperla/deep_learning_and_the_game_of_go#12]
Repro (commit b19a82, python 3.6.8):

    (cd code && python -c 'from dlgo.nn.load_mnist import load_data; load_data()')

Expected result:

    Data to silently load.

Actual result:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/jehenrik/srchome/3pmod/deep_learning_and_the_game_of_go/code/dlgo/nn/load_mnist.py", line 30, in load_data
        train_data, validation_data, test_data = pickle.load(f)  # <4>
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x90 in position 614: ordinal not in range(128)

I can confirm the data loads under python 2.7.15.

My understanding is that pickled data does not survive major python version upgrade.

Before I realized that chapter 6 has code that pulls mnist from keras.datasets, I did the same thing from the standalone pip package called "mnist".

I'm happy to fix the problem, but I don't understand what "fixed" means here.  The pickled file serves two purposes:

1) The offline developer can build and train the model without access to the network.  keras.datasets pulls the data from s3.
2) The reader of chapter 5 can learn about neural networks in a low level fashion.  No knowledge of keras whatsoever is required, not even in an import statement.

If we don't need either, we can just pull from mnist and delete the pickle.
If we want 1), we could write a routine to download from the network and save the pickle with the current python flavor to the local disk.
If we want 2), we could serialize and deserialize to some format more stable than pickle.

**Comment by maxpumperla** [comment]
@jeffhgs thanks for your feedback. that loading mnist the way described in chapter 5 is unfortunate, we should fix that (i.e. give py3 users a way to make it run by patching the current version in the least intrusive way possible).

Chapter 5 is meant to be standalone, for absolute beginners. It shows how getting the data is usually part of the problem you have to solve before running a DL algorithm. In contrast, chapter 6 shows how Keras abstracts this away almost magically (as so many other things it does well).

I didn't want to refer to the `S3` hosted Keras version of MNIST (which uses `npz` and is py2/3 compatible) in the book initially, but maybe we should have.

Alright, having said that, the encoding issue should be solvable with this:

```python
 import gzip, pickle

with gzip.open('mnist.pkl.gz', 'rb') as f:
    data = pickle._Unpickler(f)
    data.encoding = 'latin1'  # set encoding
    train, _, test = data.load()
```

Would you mind testing this suggestion and submitting a PR against master for this? Just asking, since you offered help. Thanks! Best, Max

**Comment by jeffhgs** [comment]
I will test the flags and get back to you.

**Comment by jeffhgs** [comment]
Pull request opened.  This seems to be a clear case of a buxfix, so per guidelines opened against the master branch.  Please review.

https://github.com/maxpumperla/deep_learning_and_the_game_of_go/pull/15

**Comment by jeffhgs** [comment]
Note that I also changed this to make it run on python 3:

-    return zip(features, labels)  # <3>
+    return list(zip(features, labels))  # <3>

Can we drop the zip as well?

**Comment by jeffhgs** [comment]
Without the list(...), I get:

    Traceback (most recent call last):
      File "test_nn.py", line 48, in <module>
        BoardTest().main()
      File "test_nn.py", line 44, in main
        self.test_net_one_layer()
      File "test_nn.py", line 41, in test_net_one_layer
        self.test_net_one_layer_once()
      File "test_nn.py", line 25, in test_net_one_layer_once
        training_data = self.limit_data(self.training_data, 500)
      File "test_nn.py", line 21, in limit_data
        return data[:n]
    TypeError: 'zip' object is not subscriptable

**Comment by jeffhgs** [comment]
But actually I just discovered a worse problem.  Under python 2.7 the new unpickling code crashes like so:

      File "/Users/jehenrik/srchome/3pmod/deep_learning_and_the_game_of_go/code/dlgo/nn/load_mnist.py", line 27, in load_data
        data = pickle._Unpickler(f)
    AttributeError: 'module' object has no attribute '_Unpickler'

**Comment by jeffhgs** [comment]
Closing PR, as I'm not sure how you want to proceed.  I personally would be fine dropping support for python 2.7, but that's of course you're call.

If it were up to me, the requirement I would drop is not downloading from the net.

Let me know how you'd like to proceed.

**Comment by maxpumperla** [comment]
@jeffhgs I think your PR can be salvaged. `zip` can't be removed, but wrapping with `list` is needed. Good catch. See my comment in your PR

**Comment by jeffhgs** [comment]
Resolved by https://github.com/maxpumperla/deep_learning_and_the_game_of_go/pull/18
