### ISSUE TITLE
Chapter 5 final code missing from repo

### ISSUE THREAD

**Issue by jeffhgs** [maxpumperla/deep_learning_and_the_game_of_go#14]
Without any "this is an exercise to the reader" type of fair warning, the chapter 5 code listings seem to make several tweaks (Dropout, etc) that do not seem to be present in the github repo.

Did you leave the final code out on purpose?  Did you say that anywhere?

If not, do you have a copy of the final chapter 5 code anywhere?  It seems to me like it would be worth including in the repo.

**Comment by maxpumperla** [comment]
@jeffhgs what? chapter 5 has dropout? :D I'm not aware of that. The code should not have changed in the last month and `master` and `chapter_5` _should_ be in sync. Am I missing something?

**Comment by maxpumperla** [comment]
https://github.com/maxpumperla/deep_learning_and_the_game_of_go/tree/master/code/dlgo/nn

https://github.com/maxpumperla/deep_learning_and_the_game_of_go/tree/chapter_5/code/dlgo/nn

**Comment by maxpumperla** [comment]
or do you mean chapter 6?

**Comment by jeffhgs** [comment]
My bad.

Instead of rescuing this confusing conversation, I'm going to let it die and start a new one, hopefully less confusing.
