### ISSUE TITLE
What should representation means

### ISSUE THREAD

**Issue by tychota** [maxpumperla/deep_learning_and_the_game_of_go#2]
https://github.com/maxpumperla/deep_learning_and_the_game_of_go/blob/958a0aed2951ce8930b65abd4f059fedd366f05f/code/dlgo/goboard.py#L164

`self._representation()` does not exist !!

Is it `self._hash`

**Comment by maxpumperla** [comment]
good catch, thank you! (will be updated soon)

**Comment by maxpumperla** [comment]
fixed. thanks again!

https://github.com/maxpumperla/deep_learning_and_the_game_of_go/blob/master/code/dlgo/goboard.py#L167
