### ISSUE TITLE
dlgo/networks not present (are in chapter 9 branch)

### ISSUE THREAD

**Issue by mphuget** [maxpumperla/deep_learning_and_the_game_of_go#4]
Just to mention the networks submodule as presented in Chapter 7 of the book is not here but we can find it in chapter9 branch

**Comment by maxpumperla** [comment]
@mphuget can you please clarify? They seem to be there

https://github.com/maxpumperla/deep_learning_and_the_game_of_go/tree/master/code/dlgo/networks

**Comment by mphuget** [comment]
In a previous version of the MEAP, for chapter 7, it was written to use the networks submodule but on the git repository, this submodule was not part of chapter 7 but in chapter 9.

**Comment by maxpumperla** [comment]
ok, so no problems anymore, right? I can't keep track of earlier MEAP versions, they're just early access / WIP. thanks
