### ISSUE TITLE
chapter 8:could you help me to play with gnugo?

### ISSUE THREAD

**Issue by xhw98** [maxpumperla/deep_learning_and_the_game_of_go#57]
when i read chapter 8 of gtp command ,i cant find how to use command to play with gnugo,i already installed gnugo and can play it in gogui ,but i dont know how to setup the chapter agent in command,thanks for your help!

**Comment by xhw98** [comment]
it seems that i need to set gnugo.exe in command like this?"C:\Program Files (x86)\GoGui\gogui-twogtp.exe" -black "python play_local gtp policy --read-file=tmp\savedmodel" -white "C:\gnugo\gnugo --mode gtp --level 0" -size 19 -komi 7.5 -verbose -auto

**Comment by xhw98** [comment]
when i run the play_local.py,it rasied like this :
Traceback (most recent call last):
  File "D:/ADWA/allenxxx-deep_learning_and_the_game_of_go-master/deep_learning_and_the_game_of_go/code/dlgo/gtp/play_local.py", line 152, in <module>
    handicap=0, opponent='pachi', )
  File "D:/ADWA/allenxxx-deep_learning_and_the_game_of_go-master/deep_learning_and_the_game_of_go/code/dlgo/gtp/play_local.py", line 37, in __init__
    cmd, stdin=pipe, stdout=pipe  # <5>
it means i dont set up opponet bot rightly?

**Comment by xhw98** [comment]
FileNotFoundError

**Comment by maxpumperla** [comment]
right, you need to install `pachi` as well to make that work.
