### ISSUE TITLE
chapter7   server in httpfrontend cannot work

### ISSUE THREAD

**Issue by activate-an** [maxpumperla/deep_learning_and_the_game_of_go#62]
when i run the server in httpforntend  ,it will give me a web ,but i cannot click it ,because it will be say :**404 NO Found   The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.** 

anyone can help me

**Comment by maxpumperla** [comment]
well, what URL shows up?

**Comment by VideoPac** [comment]
I had to add www to the URL from the book.
So in index_processor, you have to put:
kgs_url='https://www.u-go.net/gamerecords/'

**Comment by activate-an** [comment]
I have solved the problem. thank you very much @maxpumperla   @VideoPac

**Comment by VideoPac** [comment]
@activate-an you very welcome :)
hey given that we are reading the same chapter apparently, can you take a look at the issues I just opened. Can you make the code work? I can't...
