### ISSUE TITLE
chapter 12  how to play the ac-agent

### ISSUE THREAD

**Issue by activate-an** [maxpumperla/deep_learning_and_the_game_of_go#64]
When I get ac-agent through reinforcing learning, how can i play it, i see a web-demo in chapter-8,but what i can add in the behind "http://127.0.0.1:5000/" .  for example, i can add "static/play_predict_19.html" in the behind "http://127.0.0.1:5000/" to play with the predict-agent.

**Comment by maxpumperla** [comment]
you can add a bot in `static`, as you already figured out, e.g.:

https://github.com/maxpumperla/deep_learning_and_the_game_of_go/blob/master/code/dlgo/httpfrontend/static/play_pg_99.html#L214

in this example the bot name is `pg`.  you register this map by putting the key `pg` in the bot map, like here:

https://github.com/maxpumperla/deep_learning_and_the_game_of_go/blob/0797b3eef3c74f6be0a0ed39c719767978ef9f55/code/web_demo.py#L24

you can do this with your own bots in the same way

**Comment by activate-an** [comment]
I know ,You mean I need to add a bot in static by  myself @maxpumperla    Is that right？

**Comment by maxpumperla** [comment]
yes, exactly! if it helps, try to remove one of the existing once and then put them back in to get a feeling for how it works.
