### ISSUE TITLE
Playable Demos don't exist

### ISSUE THREAD

**Issue by brogers-tech** [maxpumperla/deep_learning_and_the_game_of_go#91]
It appears like the playable demos linked in the readme no longer exist.

**Comment by macfergus** [comment]
Hi @brogers-tech, thanks for the heads up. I moved them to another server a couple weeks ago but did not update all the links. Try them out now at:

 - https://demos.badukai.com/static/play_predict_19.html
 - https://demos.badukai.com/static/play_pg_99.html
 - https://demos.badukai.com/static/play_mcts_55.html

**Comment by brogers-tech** [comment]
Broken links are fixed.  Thanks!
