### ISSUE TITLE
Chapter 7 no pass and resign moves

### ISSUE THREAD

**Issue by arisliang** [maxpumperla/deep_learning_and_the_game_of_go#97]
Just curious, noticed this [code](https://github.com/maxpumperla/deep_learning_and_the_game_of_go/blob/282aa5ca3691e9db91a0a04eeb63543a5325580a/code/dlgo/data/processor.py#L116) seems to skip the move if it's not a point. If that's the case, isn't it the network it trained will always tend to fill up the board, even if it may be better to just resign if the game state is very unfavorable?

**Comment by macfergus** [comment]
Hi @arisliang, this is a great question. There are several options for handling pass/resign.

One is to use heuristics -- for example, you might have the bot pass whenever the human opponent passes. That's not an ideal competitive strategy, but could be good enough if people are playing the bot just for fun. See section 8.5 in the book for some examples, or here https://github.com/maxpumperla/deep_learning_and_the_game_of_go/blob/chapter_9/code/dlgo/agent/termination.py

Another is to treat pass or resign as just another move, and train the network to predict those. The zero-style implementation in chapter 14 does that for pass (but not resign) https://github.com/maxpumperla/deep_learning_and_the_game_of_go/blob/chapter_14/code/dlgo/zero/encoder.py#L42

Finally, you can use a value network to decide when to resign. A value network is a neural network that estimates which player is ahead in the game, and by how much. Value networks are covered in ch 11 - 14 in the book. Once you have a trained value network, you can add a rule like "when my chance in the game drops below 0.1, resign"

Hope that helps!

**Comment by arisliang** [comment]
Thanks, didn't realise the question can reach out to later chapters, nice link up to the later chapters and code. Will check them out together.
